# Generated by Django 3.1.4 on 2020-12-11 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channelId', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('channelTitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('videoId', models.CharField(blank=True, max_length=150, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('publishedAt', models.DateTimeField(blank=True, db_index=True, default=datetime.datetime.now)),
                ('thumbnail', models.TextField(blank=True)),
                ('channelId', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-publishedAt'],
            },
        ),
    ]
