# Generated by Django 3.1.4 on 2020-12-11 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fetch_Video', '0002_auto_20201211_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['channelId']},
        ),
    ]
