# Generated by Django 3.1.4 on 2020-12-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fetch_Video', '0003_auto_20201211_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='channel_Id',
        ),
        migrations.AddField(
            model_name='video',
            name='channelId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
